package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"reflect"
	"strings"
	"time"
)

func gmbRouteList() []route {
	var routes []route

	resp, err := http.Get("https://data.etagmb.gov.hk/route")

	if err != nil {
		log.Fatalln(err)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatalln(err)
	}

	// Autogenerated via https://mholt.github.io/json-to-go/
	type RoutesJsonResponse struct {
		Type               string    `json:"type"`
		Version            string    `json:"version"`
		GeneratedTimestamp time.Time `json:"generated_timestamp"`
		Data               struct {
			Routes struct {
				Hki []string `json:"HKI"`
				Kln []string `json:"KLN"`
				Nt  []string `json:"NT"`
			} `json:"routes"`
			DataTimestamp time.Time `json:"data_timestamp"`
		} `json:"data"`
	}

	var routesJsonResponse RoutesJsonResponse
	err = json.Unmarshal(body, &routesJsonResponse)
	if err != nil {
		fmt.Println(err)
	}

	// Iterating over HKI, KLN and NT regions
	regionalRoutes := routesJsonResponse.Data.Routes

	values := reflect.ValueOf(regionalRoutes)
	types := values.Type()
	for i := 0; i < values.NumField(); i++ {
		regionName := types.Field(i).Name
		for _, routeNo := range values.Field(i).Interface().([]string) {
			resp, err := http.Get(fmt.Sprintf("https://data.etagmb.gov.hk/route/%s/%s", strings.ToUpper(regionName), routeNo))

			if err != nil {
				log.Fatalln(err)
			}

			body, err := io.ReadAll(resp.Body)
			if err != nil {
				log.Fatalln(err)
			}

			type RouteJsonResponse struct {
				Type               string    `json:"type"`
				Version            string    `json:"version"`
				GeneratedTimestamp time.Time `json:"generated_timestamp"`
				Data               []struct {
					RouteID       int    `json:"route_id"`
					Region        string `json:"region"`
					RouteCode     string `json:"route_code"`
					DescriptionTc string `json:"description_tc"`
					DescriptionSc string `json:"description_sc"`
					DescriptionEn string `json:"description_en"`
					Directions    []struct {
						RouteSeq  int    `json:"route_seq"`
						OrigTc    string `json:"orig_tc"`
						OrigSc    string `json:"orig_sc"`
						OrigEn    string `json:"orig_en"`
						DestTc    string `json:"dest_tc"`
						DestSc    string `json:"dest_sc"`
						DestEn    string `json:"dest_en"`
						RemarksTc any    `json:"remarks_tc"`
						RemarksSc any    `json:"remarks_sc"`
						RemarksEn any    `json:"remarks_en"`
						Headways  []struct {
							Weekdays       []bool `json:"weekdays"`
							PublicHoliday  bool   `json:"public_holiday"`
							HeadwaySeq     int    `json:"headway_seq"`
							StartTime      string `json:"start_time"`
							EndTime        string `json:"end_time"`
							Frequency      int    `json:"frequency"`
							FrequencyUpper any    `json:"frequency_upper"`
						} `json:"headways"`
						DataTimestamp time.Time `json:"data_timestamp"`
					} `json:"directions"`
					DataTimestamp time.Time `json:"data_timestamp"`
				} `json:"data"`
			}

			var routeJsonResponse RouteJsonResponse
			err = json.Unmarshal(body, &routeJsonResponse)
			if err != nil {
				fmt.Println(err)
			}

			for _, routeInfo := range routeJsonResponse.Data {
				for _, direction := range routeInfo.Directions {
					newRoute := route{
						RouteNo:       routeInfo.RouteCode,
						Region:        routeInfo.Region,
						Company:       "GMB",
						Bound:         getBound(direction.RouteSeq),
						OrigEn:        direction.OrigEn,
						OrigTc:        direction.OrigTc,
						OrigSc:        direction.OrigSc,
						DestEn:        direction.DestEn,
						DestTc:        direction.DestTc,
						DestSc:        direction.DestSc,
						DescriptionEn: routeInfo.DescriptionEn,
						DescriptionSc: routeInfo.DescriptionSc,
						DescriptionTc: routeInfo.DescriptionTc,
						GmbRouteId:    routeInfo.RouteID,
					}
					routes = append(routes, newRoute)
				}

			}
			// time.Sleep(15 * time.Second)
		}
	}

	return routes
}

func getBound(routeSeq int) string {
	if routeSeq == 1 {
		return "O"
	} else if routeSeq == 2 {
		return "I"
	} else {
		return "UNDEFINED"
	}
}
