// This should not really be committed but I want to keep it here

package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/joho/godotenv"
)

func _transitland() {
	err := godotenv.Load()
	if err != nil {
		panic(err)
	}

	url := fmt.Sprintf("https://transit.land/api/v2/rest/stops/s-wecr2swy32-kmbtsowohang/departures?apikey=%s&include_alerts=true&next=10000", os.Getenv("TRANSITLAND_API_KEY"))

	resp, err := http.Get(url)

	if err != nil {
		log.Fatalln(err)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatalln(err)
	}

	// Autogenerated via https://mholt.github.io/json-to-go/
	type JsonResponse struct {
		Stops []struct {
			Alerts     []any `json:"alerts"`
			Children   any   `json:"children"`
			Departures []struct {
				Arrival struct {
					Delay          any       `json:"delay"`
					Estimated      any       `json:"estimated"`
					EstimatedDelay any       `json:"estimated_delay"`
					EstimatedLocal any       `json:"estimated_local"`
					EstimatedUtc   any       `json:"estimated_utc"`
					Scheduled      string    `json:"scheduled"`
					ScheduledLocal time.Time `json:"scheduled_local"`
					ScheduledUtc   time.Time `json:"scheduled_utc"`
					Uncertainty    any       `json:"uncertainty"`
				} `json:"arrival"`
				ArrivalTime       string `json:"arrival_time"`
				ContinuousDropOff any    `json:"continuous_drop_off"`
				ContinuousPickup  any    `json:"continuous_pickup"`
				Date              string `json:"date"`
				Departure         struct {
					Delay          any       `json:"delay"`
					Estimated      any       `json:"estimated"`
					EstimatedDelay any       `json:"estimated_delay"`
					EstimatedLocal any       `json:"estimated_local"`
					EstimatedUtc   any       `json:"estimated_utc"`
					Scheduled      string    `json:"scheduled"`
					ScheduledLocal time.Time `json:"scheduled_local"`
					ScheduledUtc   time.Time `json:"scheduled_utc"`
					Uncertainty    any       `json:"uncertainty"`
				} `json:"departure"`
				DepartureTime        string  `json:"departure_time"`
				DropOffType          int     `json:"drop_off_type"`
				Interpolated         int     `json:"interpolated"`
				PickupType           int     `json:"pickup_type"`
				ScheduleRelationship string  `json:"schedule_relationship"`
				ServiceDate          string  `json:"service_date"`
				ShapeDistTraveled    float64 `json:"shape_dist_traveled"`
				StopHeadsign         any     `json:"stop_headsign"`
				StopSequence         int     `json:"stop_sequence"`
				Timepoint            int     `json:"timepoint"`
				Trip                 struct {
					Alerts       []any `json:"alerts"`
					BikesAllowed any   `json:"bikes_allowed"`
					BlockID      any   `json:"block_id"`
					DirectionID  int   `json:"direction_id"`
					Frequencies  []any `json:"frequencies"`
					ID           int64 `json:"id"`
					Route        struct {
						Agency struct {
							AgencyID   string `json:"agency_id"`
							AgencyName string `json:"agency_name"`
							Alerts     []any  `json:"alerts"`
							ID         int    `json:"id"`
							OnestopID  string `json:"onestop_id"`
						} `json:"agency"`
						Alerts            []any  `json:"alerts"`
						ContinuousDropOff any    `json:"continuous_drop_off"`
						ContinuousPickup  any    `json:"continuous_pickup"`
						ID                int    `json:"id"`
						OnestopID         string `json:"onestop_id"`
						RouteColor        any    `json:"route_color"`
						RouteDesc         any    `json:"route_desc"`
						RouteID           string `json:"route_id"`
						RouteLongName     string `json:"route_long_name"`
						RouteShortName    string `json:"route_short_name"`
						RouteTextColor    any    `json:"route_text_color"`
						RouteType         int    `json:"route_type"`
						RouteURL          string `json:"route_url"`
					} `json:"route"`
					ScheduleRelationship string `json:"schedule_relationship"`
					Shape                struct {
						Generated bool   `json:"generated"`
						ID        int    `json:"id"`
						ShapeID   string `json:"shape_id"`
					} `json:"shape"`
					StopPatternID        int    `json:"stop_pattern_id"`
					Timestamp            any    `json:"timestamp"`
					TripHeadsign         any    `json:"trip_headsign"`
					TripID               string `json:"trip_id"`
					TripShortName        any    `json:"trip_short_name"`
					WheelchairAccessible any    `json:"wheelchair_accessible"`
				} `json:"trip"`
			} `json:"departures"`
			FeedVersion struct {
				Feed struct {
					ID        int    `json:"id"`
					OnestopID string `json:"onestop_id"`
				} `json:"feed"`
				FetchedAt time.Time `json:"fetched_at"`
				ID        int       `json:"id"`
				Sha1      string    `json:"sha1"`
			} `json:"feed_version"`
			Geometry struct {
				Coordinates []float64 `json:"coordinates"`
				Type        string    `json:"type"`
			} `json:"geometry"`
			ID                 int    `json:"id"`
			LocationType       int    `json:"location_type"`
			OnestopID          string `json:"onestop_id"`
			Parent             any    `json:"parent"`
			PlatformCode       any    `json:"platform_code"`
			StopCode           any    `json:"stop_code"`
			StopDesc           any    `json:"stop_desc"`
			StopID             string `json:"stop_id"`
			StopName           string `json:"stop_name"`
			StopTimezone       string `json:"stop_timezone"`
			StopURL            any    `json:"stop_url"`
			TtsStopName        any    `json:"tts_stop_name"`
			WheelchairBoarding any    `json:"wheelchair_boarding"`
			ZoneID             string `json:"zone_id"`
		} `json:"stops"`
	}

	var jsonResponse JsonResponse
	err = json.Unmarshal(body, &jsonResponse)
	if err != nil {
		fmt.Println(err)
	}

	departures := jsonResponse.Stops[0].Departures
	for _, departure := range departures {
		fmt.Println(departure.ArrivalTime)
	}
}
